services:
  - type: web
    name: rasa-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: rasa run --enable-api --cors "*" --port 10000
    plan: free
    envVars:
      - key: PORT
        value: 10000

  - type: web
    name: rasa-actions
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: rasa run actions
    plan: free
